apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-file-log-t1
  annotations:
    kubernetes.io/ingress.class: t1-gw
  labels:
    global: "true"
config:
  path: "/dev/stdout"
plugin: file-log
---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-correlation-id-t1
  annotations:
    kubernetes.io/ingress.class: t1-gw
  labels:
    global: "true"
config:
  header_name: Tenant1-Kong-Request-ID
  generator: uuid#counter
  echo_downstream: true
plugin: correlation-id
