---
kind: GatewayConfiguration
apiVersion: gateway-operator.konghq.com/v1beta1
metadata:
  name: t1-gw
  namespace: t1-gw
spec:
  dataPlaneOptions:
    deployment:
      podTemplateSpec:
        spec:
          containers:
            - name: proxy
              image: kong:3.8.0
              readinessProbe:
                initialDelaySeconds: 1
                periodSeconds: 1
  controlPlaneOptions:
    deployment:
      podTemplateSpec:
        spec:
          containers:
            - name: controller
              image: kong/kubernetes-ingress-controller:3.3.0
              env:
                - name: CONTROLLER_LOG_LEVEL
                  value: debug
                - name: CONTROLLER_INGRESS_CLASS
                  value: t1-gw
