deployment:
  test:
    enabled: false

controller:
  proxy:
    nameOverride: "{{ .Release.Name }}-gateway-proxy"

  enabled: true
  image:
    repository: "kong/kubernetes-ingress-controller"
    tag: "3.3.1"

  deployment:
    kong:
      enabled: false

  ingressController:
    enabled: true
    env:
      gateway_api_controller_name:	konghq.com/kic-gateway-controller-internal
    # ingressClass: "soap" activate only if you're using ingress class
    # gateway_to_reconcile: "soap-api/kong2" activate only if you're using a single gatewayclass for multiple gateways
    gatewayDiscovery:
      enabled: true
      generateAdminApiService: true


gateway:
  enabled: true
  deployment:
    kong:
      enabled: true
  image:
    repository: "kong/kong-gateway"
    tag: "3.4.3.13"
    effectiveSemver: 3.4.3
    pullPolicy: IfNotPresent

    # pullSecrets:
    #   - regcred
  env:
    database: "off"
  admin:
    enabled: true
    type: ClusterIP
    clusterIP: None
    ingress:
      enabled: false

  proxy:
    http:
      servicePort: 8000

    tls:
      servicePort: 8443


  ingressController:
    enabled: false

  env:
    database: "off"
    # proxy_listen: "0.0.0.0:8000 ipv6only=off, 0.0.0.0:8443 http2 ssl ipv6only=off"
    # admin_listen: "0.0.0.0:8444 http2 ssl ipv6only=off"
    # status_listen: "0.0.0.0:8100 ipv6only=off"
  manager:
    enabled: true
    type: ClusterIP
    ingress:
      enabled: false